// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAcYWVZisu7LkpG43LcKOKJsavj-qpMoE',
    appId: '1:686308175049:web:0c9a7d2c28d0ad09c5b118',
    messagingSenderId: '686308175049',
    projectId: 'marklin-bluetooth',
    authDomain: 'marklin-bluetooth.firebaseapp.com',
    databaseURL: 'https://marklin-bluetooth-default-rtdb.firebaseio.com',
    storageBucket: 'marklin-bluetooth.appspot.com',
    measurementId: 'G-5MZ2Z91XMQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCi0a0wfSRJph76mWOU4WW8YnU4AYcnYz8',
    appId: '1:686308175049:android:e8adba2ad8f3c28cc5b118',
    messagingSenderId: '686308175049',
    projectId: 'marklin-bluetooth',
    databaseURL: 'https://marklin-bluetooth-default-rtdb.firebaseio.com',
    storageBucket: 'marklin-bluetooth.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAY5zimAZsm-VyjbBw7O9yaqCdiPF7sp7Y',
    appId: '1:686308175049:ios:82442a3cd788c5a8c5b118',
    messagingSenderId: '686308175049',
    projectId: 'marklin-bluetooth',
    databaseURL: 'https://marklin-bluetooth-default-rtdb.firebaseio.com',
    storageBucket: 'marklin-bluetooth.firebasestorage.app',
    iosBundleId: 'com.agardh.marklinBluetooth',
  );

}